apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-storage-pv
  labels:
    type: local-storage
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/app-storage
