apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: devops-practice

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: devops-practice
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-read-pods-binding
  namespace: devops-practice
subjects:
  - kind: ServiceAccount
    name: app-service-account
    namespace: devops-practice
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
